### ISSUE TITLE
Panic in ToOuput::name

### ISSUE THREAD

**Issue by max-frai** [GuillaumeGomez/html-diff-rs#12]
Hello, there is code in lib.rs:65
`s[1..].to_owned()`
And it panics in some cases of unicode symbols. As I understand, you can't just trim first letter using this, it skips first byte, not character.

**Comment by GuillaumeGomez** [comment]
I should be using `chars` instead. Thanks for the issue, I'll fix it in the next hours.

**Comment by GuillaumeGomez** [comment]
Oh btw, can you give me a short sample of your HTML so I can add a test please?

**Comment by max-frai** [comment]
It seems that there is also bug in path generation. For example when you have such html:
```
<div>
   <img src="..."
   <div>
     <p>here will be changed content</p>
   </div>
</div>
```
Your code would generate path like `/div[1]/div[2]/p[1]` when text node (p) has been changed. But it's wrong, the number in braces is index of child of declared type. `div[2]` tell us to get 2nd div child, but there is only one and the correct path is `/div[1]/div[1]/p[1]`.

**Comment by GuillaumeGomez** [comment]
That's another bug. Open another issue for it please, it's easier for me to keep tracks like this.

**Comment by max-frai** [comment]
Okay, did it. Thank you for the library, it saved me a lot of time. I'd like to propose you fix with path generation but I don't know how to make it correct for now.

**Comment by GuillaumeGomez** [comment]
You didn't give me the html with unicode character btw. :p

**Comment by GuillaumeGomez** [comment]
> Thank you for the library, it saved me a lot of time.

No problem, we needed it for `rustdoc` anyway so it's nice if other projects need it as well.

> I'd like to propose you fix with path generation but I don't know how to make it correct for now.

I *think* it's not that difficult so I don't mind fixing it at all (it's my project after all 😉 ).

**Comment by GuillaumeGomez** [comment]
I really can't find out how you made it panic so I'll wait for your unicode html sample so I can write down the test.
