### ISSUE TITLE
Add git tags corresponding to crates.io releases

### ISSUE THREAD

**Issue by devonhollowood** [GuillaumeGomez/html-diff-rs#16]
It would be nice to have git tags / github releases corresponding to the various crates.io releases. For example, I was just tracking down this rust issue: https://github.com/rust-lang/rust/issues/47728, and it would have been nice to be able to easily see what had changed between `0.0.4` and `0.0.6`.

**Comment by GuillaumeGomez** [comment]
Yes it would. I'll try to keep it in mind for next release (I'll push a tag for this one already).

**Comment by devonhollowood** [comment]
Awesome, thanks! If you are interested in going back and adding previous tags, the sha1 sums for the versions so far are:

version | sha1
-|-
0.0.1 | 7161c2081e705b58c353d7b52c3f4d3d5b47c5a8
0.0.2 | e8e079764f86a0d37b654adff98121c596599789
0.0.3 | dade0f185d464c4ef60b318cc4704daf4ff8910c
0.0.4 | 30fe11899fa31197a90ef93412f8cb7b7480b1af
0.0.5 | bd49a8a281f903d418f1144207b38ed97f3d2954
0.0.6 | 9bc85fab3bfed23e6219a765b0571eed1e85cd53

**Comment by GuillaumeGomez** [comment]
Well, you took the effort to look for them so I'll add them.

**Comment by devonhollowood** [comment]
Nice, thanks.

**Comment by GuillaumeGomez** [comment]
Ok, they're all there. Thanks for reporting!
